### ISSUE TITLE
[BUG] conflicts with macOS AirPlay receiver

### ISSUE THREAD

**Issue by make-believe-agency** [jerlendds/osintbuddy#48]
**Describe the bug**
Osintbuddy main port conflict with macOS AirPlay.

**To Reproduce**
Attempt to launch osintbuddy on port 5000 (default)

**Expected behavior**
Not to conflict with ports OS uses by default

**Desktop (please complete the following information):**
- macOS

**Additional context**
macOS users need to turn of AirPlay receiver to use osintbuddy

**Comment by jerlendds** [comment]
Ah that is in issue, I'll update the port to `8000`. Thanks for bringing this up! I unfortunately don't have much experience with Apple systems

**Comment by jerlendds** [comment]
That should be a bit better now:
![image](https://github.com/jerlendds/osintbuddy/assets/29207058/570cc521-b44c-4724-a599-094c0d17dfe3)

[commit 728562a](https://github.com/jerlendds/osintbuddy/commit/728562af494440463cb701710e3ae393cbe1dec6)

**Comment by make-believe-agency** [comment]
Wouldn't it be better to set it up to use a range of ports uncommonly used? A simple google would uncover the fact port 8000 is quite a commonly used one, and likely something that's already going to be used on your target user's system

**Comment by jerlendds** [comment]
I chose 8000 due to it being common as I saw Django using it and well this is ultimately a web application after all. I didn't really anticipate users running multiple systems. Do you think thats common enough to be worth changing the port for? I do think it should be more configurable either way though and I've created a task for that improvement on the trello board
