### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Draketheb4dass** [jerlendds/osintbuddy#69]
**Bug Description:**

Error response from daemon: Ports are not available: exposing port TCP 0.0.0.0:7000 -> 0.0.0.0:0: listen tcp4 0.0.0.0:7000: bind: address already in use.

**How to Reproduce:**

1. Install Docker and follow the README using a Mac M1 Sequoia 15.0

**Expected behavior:**
App should run
...

**Screenshots & Logs:**
![image](https://github.com/user-attachments/assets/5ce97c01-45d1-4521-9b57-a34eb893f75a)

Please run `./launcher debug_send` to upload and get a public link to your log files.
This will help us with debugging and solving any issues.
https://paste.c-net.org/PigeonVoodoo
**Environment:**

- OS: MacOSX Sequoia 15.0
- Browser: Chrome

**Additional context:**
Port 7000 is already being used by: ControlCenter (a mac system app)
...

**Comment by ipsax** [comment]
Hey @Draketheb4dass , thanks for reporting this! This is a known bug that I havent bothered addressing since the rewrite will alleviate this + change the tech stack lots (lighter and faster :sunglasses: ). As a workaround you can try turning off that mac service OR remapping the ports in the compose file: `osintbuddy/ob/alpha-compose.yml`. I'm currently working on pitch decks for the project rather than focusing on the rewrite so we can hopefully get some funding for this project. Most of the pitch will be available at an undocumented link -> `https://graphowls.com/investors/pitch` once ready but in the meantime heres a quick preview if you're curious :) ->

![image](https://github.com/user-attachments/assets/016d6cc8-c055-4536-a4be-059a1aaf6c5e)

**Comment by Draketheb4dass** [comment]
I have temporarily disable the service(Airdrop service on Mac), but has had another issue  which I might open another issue for. 
```
[Error grabbing logs: invalid character '\x00' looking for beginning of value](https://stackoverflow.com/questions/46843711/docker-error-grabbing-logs-invalid-character-x00-looking-for-beginning-of-v)
```
BTW this link : https://graphowls.com/investors/pitch is not working.
